
package com.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2019-03-09T10:56:58.147+05:30
 * Generated source version: 2.7.9
 * 
 */
 
public class EmployeeDetailsWS_PortTypeServer{

    protected EmployeeDetailsWS_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new com.soap.EmployeeDetailsWS();
        String address = "http://localhost:9090/EmployeeDetailsWSPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new EmployeeDetailsWS_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 